matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm install;
      npm run sms:build-desktop;
      npm run desktop:full;
    fi
   
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
