matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo $CERTIFICATE_OSX_P12 | base64 --decode > keystore.p12;
      security create-keychain -p $KEYCHAIN_PASSWORD build.keychain;
      security default-keychain -s build.keychain;
      security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain;
      security import keystore.p12 -k build.keychain -T /usr/bin/codesign;
      security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD build.keychain;
      npm install;
      npm run sms:build-desktop;
      npm run desktop:full;
    fi
   
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
